# Generated by Django 3.0.3 on 2020-02-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices_collect', '0002_auto_20200209_1302'),
        ('story_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndoorDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cpu_name', models.CharField(max_length=256)),
                ('screen_size', models.CharField(max_length=64)),
                ('system_os_v', models.CharField(max_length=64)),
                ('manufactory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices_collect.Manufactory')),
            ],
        ),
        migrations.CreateModel(
            name='UseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices_analysis.IndoorDevices')),
                ('test_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_analysis.TestUser')),
            ],
        ),
    ]
