# Generated by Django 3.0.3 on 2020-02-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('cpu_name', models.CharField(max_length=255)),
                ('screen_size', models.CharField(max_length=63)),
                ('system_os_v', models.CharField(max_length=63)),
            ],
        ),
    ]
