# Generated by Django 3.0.3 on 2020-02-09 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices_collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_type', models.BooleanField(default=True)),
                ('result', models.CharField(max_length=256)),
                ('generated_time', models.DateTimeField(default=datetime.datetime(2020, 2, 9, 5, 2, 38, 196206, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactory_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='devices',
            name='cpu_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='devices',
            name='screen_size',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='devices',
            name='system_os_v',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='devices',
            name='manufactory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices_collect.Manufactory'),
        ),
    ]
