# Generated by Django 3.0.3 on 2020-02-09 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story_analysis', '0002_category_c_id'),
        ('devices_collect', '0005_auto_20200209_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='collectdevices',
            name='generated_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 9, 20, 13, 139368, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2020, 2, 9, 9, 20, 13, 140366, tzinfo=utc))),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_analysis.TestUser')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices_collect.CollectDevices')),
            ],
        ),
        migrations.AlterField(
            model_name='collectdevices',
            name='collect_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices_collect.CollectType'),
        ),
    ]
