# Generated by Django 3.0.3 on 2020-02-09 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices_collect', '0006_auto_20200209_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 9, 23, 17, 341223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='collectdevices',
            name='generated_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 9, 23, 17, 340228, tzinfo=utc)),
        ),
    ]
