# Generated by Django 3.0.3 on 2020-02-09 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
